/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by Keycloakify

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "carp-custom-theme";

export const themeNames: ThemeName[] = ["carp-custom-theme"];

export type KcEnvName = "MY_ENV_VARIABLE";

export const kcEnvNames: KcEnvName[] = ["MY_ENV_VARIABLE"];

export const kcEnvDefaults: Record<KcEnvName, string> = {
  "MY_ENV_VARIABLE": ""
};

export type KcContext =
    | import("./login/KcContext").KcContext
    ;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(
    props: {
        kcContext: KcContext;
        fallback?: ReactNode;
    }
) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login": return <KcLoginPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}

/* prettier-ignore-end */
